apiVersion: v1
data:
  host: bW9uZ28tc2VydmljZQ==
kind: Secret
metadata:
  name: mongo-secret
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-deployment
  labels:
    app: node-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node-server
  template:
    metadata:
      name: node-server
      labels:
        app: node-server
    spec:
      containers:
      - name: server-js-ceiba 
        env: 
          - name: HOST
            valueFrom: 
              secretKeyRef: 
                name: mongo-secret
                key: host
        image: serverjs-ceiba-k8s 
        imagePullPolicy: IfNotPresent 
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: node-service
  labels:
    app: node-service
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  selector:
    app: node-server
    
