apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-deployment
  labels:
    app: mongo-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo-server
  template:
    metadata:
      name: mongo-server
      labels:
        app: mongo-server
    spec:
      containers:
      - name: mongodb-container
        imagePullPolicy: IfNotPresent
        image: mongo-ceiba
        ports:
        - containerPort: 27017 
---
apiVersion: v1
kind: Service
metadata:
  name: mongo-service
  labels:
    app: mongo-service
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
  selector:
    app: mongo-server
    
